spring:
    datasource:
        username: root
        password: admin
        url: jdbc:mysql://localhost:3306/grades
    jpa:
        hibernate:
            ddl-auto: update
            
server:
    port: 8888